# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Notes
tagline:          Harsh's mind dumps
description:      "Random notes over troubleshooting Big Data Systems."
url:              https://qwertymaniac.github.io/notes/
baseurl:          /notes/

author:
  name:           'Harsh J'
  url:            http://harshj.com

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/QwertyManiac/notes
